name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake
    steps:
      - name: Checkout repo
      uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: g-rashmi
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          pull: true              # ‚Üê IMPORTANT FIX
          message: "Generated snake animation"
          add: "dist"
